"""added timestamp to notification

Revision ID: 207e2ced3284
Revises: 
Create Date: 2026-02-27 02:08:37.776337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207e2ced3284'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
